# syntax=docker/dockerfile:1
ARG NODE_VERSION=20.12.2

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV production


WORKDIR /usr/src/app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

COPY . .

RUN chown -R node:node /usr/src/app/uploads
USER node

EXPOSE 8000

CMD node api.js
